#!/usr/bin/env python3
"""
Wrapper entrypoint for defora_cli.deforumation_dashboard.
"""
from defora_cli import deforumation_dashboard as _dashboard


if __name__ == "__main__":
    _dashboard.main()
